export const onInsertChild = Symbol('dominative.onInsertChild')
export const onRemoveChild = Symbol('dominative.onRemoveChild')
export const onAddEventListener = Symbol('dominative.onAddEventListener')
export const onRemoveEventListener = Symbol('dominative.onRemoveEventListener')
export const onSetAttributeNS = Symbol('dominative.onSetAttributeNS')
export const onGetAttributeNS = Symbol('dominative.onGetAttributeNS')
export const onRemoveAttributeNS = Symbol('dominative.onRemoveAttributeNS')
export const onBeingInserted = Symbol('dominative.onBeingInserted')
export const onBeingRemoved = Symbol('dominative.onBeingRemoved')
export const setPropOnParent = Symbol('dominative.setPropOnParent')

export const isNative = Symbol('dominative.isNative')
export const isPseudoElement = Symbol('dominative.isPseudoElement')
export const eventHandlers = Symbol('dominative.eventHandlers')
export const listUpdating = Symbol('dominative.listUpdating')
export const updateText = Symbol('dominative.updateText')
export const role = Symbol('dominative.role')
